load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_cc",
    strip_prefix = "rules_cc-master",
    urls = [
        "https://github.com/bazelbuild/rules_cc/archive/master.tar.gz",
    ],
)

http_archive(
    name = "replxx",
    type = "zip",
    url = "https://github.com/AmokHuginnsson/replxx/archive/master.zip",
    strip_prefix = "replxx-master",
)

